# Project1: Scraping a table

In [1]:
import requests
from bs4 import BeautifulSoup


#Imports the HTML into python
url = 'https://www.worldometers.info/world-population/'

page = requests.get(url)
soup = BeautifulSoup(page.text, 'lxml') # lxml vs html.parser : lxml in faster but has c dependencies

In [2]:
#Subsets the HTML to only get the HTML of our table needed
table = soup.find('table', class_ = 'table table-striped table-bordered table-hover table-condensed table-list')

In [3]:
print(table)

<table class="table table-striped table-bordered table-hover table-condensed table-list"><thead> <tr> <th>Year<br/> (July 1) </th><th>Population</th><th>Yearly % <br/> Change</th><th>Yearly<br/> Change</th><th>Median <br/>Age</th><th>Fertility <br/>Rate</th><th>Density <br/>(P/Km²)</th><th>Urban<br/> Pop %</th><th>Urban Population</th> </tr><tr> <td>2020</td> <td><strong>7,794,798,739</strong></td> <td>1.05 %</td> <td>81,330,639</td> <td>30.9</td> <td>2.47</td> <td>52</td> <td>56.2 %</td> <td>4,378,993,944</td> </tr> <tr> <td>2019</td> <td><strong>7,713,468,100</strong></td> <td>1.08 %</td> <td>82,377,060</td> <td>29.8</td> <td>2.51</td> <td>52</td> <td>55.7 %</td> <td>4,299,438,618</td> </tr></thead><tbody><tr> <td>2018</td> <td><strong>7,631,091,040</strong></td> <td>1.10 %</td> <td>83,232,115</td> <td>29.8</td> <td>2.51</td> <td>51</td> <td>55.3 %</td> <td>4,219,817,318</td></tr><tr> <td>2017</td> <td><strong>7,547,858,925</strong></td> <td>1.12 %</td> <td>83,836,876</td> <td>29.8</td> <td>2.51</td> <td>51</td> <td>54.9 %</td> <td>4,140,188,594</td> </tr><tr> <td>2016</td> <td><strong>7,464,022,049</strong></td> <td>1.14 %</td> <td>84,224,910</td> <td>29.8</td> <td>2.51</td> <td>50</td> <td>54.4 %</td> <td>4,060,652,683</td> </tr><tr> <td>2015</td> <td><strong>7,379,797,139</strong></td> <td>1.19 %</td> <td>84,594,707</td> <td>30</td> <td>2.52</td> <td>50</td> <td>54.0 %</td> <td>3,981,497,663</td> </tr><tr> <td>2010</td> <td><strong>6,956,823,603</strong></td> <td>1.24 %</td> <td>82,983,315</td> <td>28</td> <td>2.58</td> <td>47</td> <td>51.7 %</td> <td>3,594,868,146</td> </tr><tr> <td>2005</td> <td><strong>6,541,907,027</strong></td> <td>1.26 %</td> <td>79,682,641</td> <td>27</td> <td>2.65</td> <td>44</td> <td>49.2 %</td> <td>3,215,905,863</td> </tr><tr> <td>2000</td> <td><strong>6,143,493,823</strong></td> <td>1.35 %</td> <td>79,856,169</td> <td>26</td> <td>2.78</td> <td>41</td> <td>46.7 %</td> <td>2,868,307,513</td> </tr><tr> <td>1995</td> <td><strong>5,744,212,979</strong></td> <td>1.52 %</td> <td>83,396,384</td> <td>25</td> <td>3.01</td> <td>39</td> <td>44.8 %</td> <td>2,575,505,235</td> </tr><tr> <td>1990</td> <td><strong>5,327,231,061</strong></td> <td>1.81 %</td> <td>91,261,864</td> <td>24</td> <td>3.44</td> <td>36</td> <td>43.0 %</td> <td>2,290,228,096</td> </tr><tr> <td>1985</td> <td><strong>4,870,921,740</strong></td> <td>1.79 %</td> <td>82,583,645</td> <td>23</td><td>3.59</td> <td>33</td> <td>41.2 %</td> <td>2,007,939,063</td> </tr><tr> <td>1980</td> <td><strong>4,458,003,514</strong></td> <td>1.79 %</td> <td>75,704,582</td> <td>23</td> <td>3.86</td> <td>30</td> <td>39.3 %</td> <td>1,754,201,029</td> </tr><tr> <td>1975</td> <td><strong>4,079,480,606</strong></td> <td>1.97 %</td> <td>75,808,712</td> <td>22</td> <td>4.47</td> <td>27</td> <td>37.7 %</td> <td>1,538,624,994</td> </tr><tr> <td>1970</td> <td><strong>3,700,437,046</strong></td> <td>2.07 %</td> <td>72,170,690</td> <td>22</td><td>4.93</td> <td>25</td> <td>36.6 %</td> <td>1,354,215,496</td> </tr><tr> <td>1965</td> <td><strong>3,339,583,597</strong></td> <td>1.93 %</td> <td>60,926,770</td> <td>22</td> <td>5.02</td> <td>22</td> <td>N.A.</td> <td>N.A.</td> </tr><tr> <td>1960</td> <td><strong>3,034,949,748</strong></td> <td>1.82 %</td> <td>52,385,962</td> <td>23</td> <td>4.90</td> <td>20</td> <td>33.7 %</td> <td>1,023,845,517</td> </tr><tr> <td>1955</td> <td><strong>2,773,019,936</strong></td> <td>1.80 %</td> <td>47,317,757</td> <td>23</td> <td>4.97</td> <td>19</td> <td>N.A.</td> <td>N.A.</td></tr></tbody></table>

In [4]:
print(table.prettify())

<table class="table table-striped table-bordered table-hover table-condensed table-list">
 <thead>
  <tr>
   <th>
    Year
    <br/>
    (July 1)
   </th>
   <th>
    Population
   </th>
   <th>
    Yearly %
    <br/>
    Change
   </th>
   <th>
    Yearly
    <br/>
    Change
   </th>
   <th>
    Median
    <br/>
    Age
   </th>
   <th>
    Fertility
    <br/>
    Rate
   </th>
   <th>
    Density
    <br/>
    (P/Km²)
   </th>
   <th>
    Urban
    <br/>
    Pop %
   </th>
   <th>
    Urban Population
   </th>
  </tr>
  <tr>
   <td>
    2020
   </td>
   <td>
    <strong>
     7,794,798,739
    </strong>
   </td>
   <td>
    1.05 %
   </td>
   <td>
    81,330,639
   </td>
   <td>
    30.9
   </td>
   <td>
    2.47
   </td>
   <td>
    52
   </td>
   <td>
    56.2 %
   </td>
   <td>
    4,378,993,944
   </td>
  </tr>
  <tr>
   <td>
    2019
   </td>
   <td>
    <strong>
     7,713,468,100
    </strong>
   </td>
   <td>
    1.08 %
   </td>
   <td>
    82,377,060
   </td>
   <td>
    29.8
   </td>
   <td>
    2.51
   </td>
   <td>
    52
   </td>
   <td>
    55.7 %
   </td>
   <td>
    4,299,438,618
   </td>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>
    2018
   </td>
   <td>
    <strong>
     7,631,091,040
    </strong>
   </td>
   <td>
    1.10 %
   </td>
   <td>
    83,232,115
   </td>
   <td>
    29.8
   </td>
   <td>
    2.51
   </td>
   <td>
    51
   </td>
   <td>
    55.3 %
   </td>
   <td>
    4,219,817,318
   </td>
  </tr>
  <tr>
   <td>
    2017
   </td>
   <td>
    <strong>
     7,547,858,925
    </strong>
   </td>
   <td>
    1.12 %
   </td>
   <td>
    83,836,876
   </td>
   <td>
    29.8
   </td>
   <td>
    2.51
   </td>
   <td>
    51
   </td>
   <td>
    54.9 %
   </td>
   <td>
    4,140,188,594
   </td>
  </tr>
  <tr>
   <td>
    2016
   </td>
   <td>
    <strong>
     7,464,022,049
    </strong>
   </td>
   <td>
    1.14 %
   </td>
   <td>
    84,224,910
   </td>
   <td>
    29.8
   </td>
   <td>
    2.51
   </td>
   <td>
    50
   </td>
   <td>
    54.4 %
   </td>
   <td>
    4,060,652,683
   </td>
  </tr>
  <tr>
   <td>
    2015
   </td>
   <td>
    <strong>
     7,379,797,139
    </strong>
   </td>
   <td>
    1.19 %
   </td>
   <td>
    84,594,707
   </td>
   <td>
    30
   </td>
   <td>
    2.52
   </td>
   <td>
    50
   </td>
   <td>
    54.0 %
   </td>
   <td>
    3,981,497,663
   </td>
  </tr>
  <tr>
   <td>
    2010
   </td>
   <td>
    <strong>
     6,956,823,603
    </strong>
   </td>
   <td>
    1.24 %
   </td>
   <td>
    82,983,315
   </td>
   <td>
    28
   </td>
   <td>
    2.58
   </td>
   <td>
    47
   </td>
   <td>
    51.7 %
   </td>
   <td>
    3,594,868,146
   </td>
  </tr>
  <tr>
   <td>
    2005
   </td>
   <td>
    <strong>
     6,541,907,027
    </strong>
   </td>
   <td>
    1.26 %
   </td>
   <td>
    79,682,641
   </td>
   <td>
    27
   </td>
   <td>
    2.65
   </td>
   <td>
    44
   </td>
   <td>
    49.2 %
   </td>
   <td>
    3,215,905,863
   </td>
  </tr>
  <tr>
   <td>
    2000
   </td>
   <td>
    <strong>
     6,143,493,823
    </strong>
   </td>
   <td>
    1.35 %
   </td>
   <td>
    79,856,169
   </td>
   <td>
    26
   </td>
   <td>
    2.78
   </td>
   <td>
    41
   </td>
   <td>
    46.7 %
   </td>
   <td>
    2,868,307,513
   </td>
  </tr>
  <tr>
   <td>
    1995
   </td>
   <td>
    <strong>
     5,744,212,979
    </strong>
   </td>
   <td>
    1.52 %
   </td>
   <td>
    83,396,384
   </td>
   <td>
    25
   </td>
   <td>
    3.01
   </td>
   <td>
    39
   </td>
   <td>
    44.8 %
   </td>
   <td>
    2,575,505,235
   </td>
  </tr>
  <tr>
   <td>
    1990
   </td>
   <td>
    <strong>
     5,327,231,061
    </strong>
   </td>
   <td>
    1.81 %
   </td>
   <td>
    91,261,864
   </td>
   <td>
    24
   </td>
   <td>
    3.44
   </td>
   <td>
    36
   </td>
   <td>
    43.0 %
   </td>
   <td>
    2,290,228,096
   </td>
  </tr>
  <tr>
   <td>
    1985
   </td>
   <td>
    <strong>
     4,870,921,740
    </strong>
   </td>
   <td>
    1.79 %
   </td>
   <td>
    82,583,645
   </td>
   <td>
    23
   </td>
   <td>
    3.59
   </td>
   <td>
    33
   </td>
   <td>
    41.2 %
   </td>
   <td>
    2,007,939,063
   </td>
  </tr>
  <tr>
   <td>
    1980
   </td>
   <td>
    <strong>
     4,458,003,514
    </strong>
   </td>
   <td>
    1.79 %
   </td>
   <td>
    75,704,582
   </td>
   <td>
    23
   </td>
   <td>
    3.86
   </td>
   <td>
    30
   </td>
   <td>
    39.3 %
   </td>
   <td>
    1,754,201,029
   </td>
  </tr>
  <tr>
   <td>
    1975
   </td>
   <td>
    <strong>
     4,079,480,606
    </strong>
   </td>
   <td>
    1.97 %
   </td>
   <td>
    75,808,712
   </td>
   <td>
    22
   </td>
   <td>
    4.47
   </td>
   <td>
    27
   </td>
   <td>
    37.7 %
   </td>
   <td>
    1,538,624,994
   </td>
  </tr>
  <tr>
   <td>
    1970
   </td>
   <td>
    <strong>
     3,700,437,046
    </strong>
   </td>
   <td>
    2.07 %
   </td>
   <td>
    72,170,690
   </td>
   <td>
    22
   </td>
   <td>
    4.93
   </td>
   <td>
    25
   </td>
   <td>
    36.6 %
   </td>
   <td>
    1,354,215,496
   </td>
  </tr>
  <tr>
   <td>
    1965
   </td>
   <td>
    <strong>
     3,339,583,597
    </strong>
   </td>
   <td>
    1.93 %
   </td>
   <td>
    60,926,770
   </td>
   <td>
    22
   </td>
   <td>
    5.02
   </td>
   <td>
    22
   </td>
   <td>
    N.A.
   </td>
   <td>
    N.A.
   </td>
  </tr>
  <tr>
   <td>
    1960
   </td>
   <td>
    <strong>
     3,034,949,748
    </strong>
   </td>
   <td>
    1.82 %
   </td>
   <td>
    52,385,962
   </td>
   <td>
    23
   </td>
   <td>
    4.90
   </td>
   <td>
    20
   </td>
   <td>
    33.7 %
   </td>
   <td>
    1,023,845,517
   </td>
  </tr>
  <tr>
   <td>
    1955
   </td>
   <td>
    <strong>
     2,773,019,936
    </strong>
   </td>
   <td>
    1.80 %
   </td>
   <td>
    47,317,757
   </td>
   <td>
    23
   </td>
   <td>
    4.97
   </td>
   <td>
    19
   </td>
   <td>
    N.A.
   </td>
   <td>
    N.A.
   </td>
  </tr>
 </tbody>
</table>

In [5]:
table.find_all('th')

[<th>Year<br/> (July 1) </th>,
 <th>Population</th>,
 <th>Yearly % <br/> Change</th>,
 <th>Yearly<br/> Change</th>,
 <th>Median <br/>Age</th>,
 <th>Fertility <br/>Rate</th>,
 <th>Density <br/>(P/Km²)</th>,
 <th>Urban<br/> Pop %</th>,
 <th>Urban Population</th>]

In [6]:
for i in table.find_all('th'):
    print(i.text.strip())

Year (July 1)
Population
Yearly %  Change
Yearly Change
Median Age
Fertility Rate
Density (P/Km²)
Urban Pop %
Urban Population

In [7]:
#Gets all the column headers of our table
headers = []
for i in table.find_all('th'):
    title = i.text.strip()
    headers.append(title)

In [8]:
print(headers)

['Year (July 1)', 'Population', 'Yearly %  Change', 'Yearly Change', 'Median Age', 'Fertility Rate', 'Density (P/Km²)', 'Urban Pop %', 'Urban Population']

In [9]:
table.find_all('tr')[1]

In [10]:
#gets all our data within the table and adds it to our list
my_list = []
for j in table.find_all('tr')[1:]:
    row_data = j.find_all('td')
    row = [tr.text for tr in row_data]
    my_list.append(row)

In [11]:
my_list

[['2020',
  '7,794,798,739',
  '1.05 %',
  '81,330,639',
  '30.9',
  '2.47',
  '52',
  '56.2 %',
  '4,378,993,944'],
 ['2019',
  '7,713,468,100',
  '1.08 %',
  '82,377,060',
  '29.8',
  '2.51',
  '52',
  '55.7 %',
  '4,299,438,618'],
 ['2018',
  '7,631,091,040',
  '1.10 %',
  '83,232,115',
  '29.8',
  '2.51',
  '51',
  '55.3 %',
  '4,219,817,318'],
 ['2017',
  '7,547,858,925',
  '1.12 %',
  '83,836,876',
  '29.8',
  '2.51',
  '51',
  '54.9 %',
  '4,140,188,594'],
 ['2016',
  '7,464,022,049',
  '1.14 %',
  '84,224,910',
  '29.8',
  '2.51',
  '50',
  '54.4 %',
  '4,060,652,683'],
 ['2015',
  '7,379,797,139',
  '1.19 %',
  '84,594,707',
  '30',
  '2.52',
  '50',
  '54.0 %',
  '3,981,497,663'],
 ['2010',
  '6,956,823,603',
  '1.24 %',
  '82,983,315',
  '28',
  '2.58',
  '47',
  '51.7 %',
  '3,594,868,146'],
 ['2005',
  '6,541,907,027',
  '1.26 %',
  '79,682,641',
  '27',
  '2.65',
  '44',
  '49.2 %',
  '3,215,905,863'],
 ['2000',
  '6,143,493,823',
  '1.35 %',
  '79,856,169',
  '26',
  '2.78',
  '41',
  '46.7 %',
  '2,868,307,513'],
 ['1995',
  '5,744,212,979',
  '1.52 %',
  '83,396,384',
  '25',
  '3.01',
  '39',
  '44.8 %',
  '2,575,505,235'],
 ['1990',
  '5,327,231,061',
  '1.81 %',
  '91,261,864',
  '24',
  '3.44',
  '36',
  '43.0 %',
  '2,290,228,096'],
 ['1985',
  '4,870,921,740',
  '1.79 %',
  '82,583,645',
  '23',
  '3.59',
  '33',
  '41.2 %',
  '2,007,939,063'],
 ['1980',
  '4,458,003,514',
  '1.79 %',
  '75,704,582',
  '23',
  '3.86',
  '30',
  '39.3 %',
  '1,754,201,029'],
 ['1975',
  '4,079,480,606',
  '1.97 %',
  '75,808,712',
  '22',
  '4.47',
  '27',
  '37.7 %',
  '1,538,624,994'],
 ['1970',
  '3,700,437,046',
  '2.07 %',
  '72,170,690',
  '22',
  '4.93',
  '25',
  '36.6 %',
  '1,354,215,496'],
 ['1965',
  '3,339,583,597',
  '1.93 %',
  '60,926,770',
  '22',
  '5.02',
  '22',
  'N.A.',
  'N.A.'],
 ['1960',
  '3,034,949,748',
  '1.82 %',
  '52,385,962',
  '23',
  '4.90',
  '20',
  '33.7 %',
  '1,023,845,517'],
 ['1955',
  '2,773,019,936',
  '1.80 %',
  '47,317,757',
  '23',
  '4.97',
  '19',
  'N.A.',
  'N.A.']]

In [ ]:
!pip install pandas

In [12]:
import pandas as pd # import numpy as np
df =  pd.DataFrame(my_list, columns = headers)

In [13]:
df

,Year (July 1),Population,Yearly % Change,Yearly Change,Median Age,Fertility Rate,Density (P/Km²),Urban Pop %,Urban Population
0,2020,"7,794,798,739",1.05 %,"81,330,639",30.9,2.47,52,56.2 %,"4,378,993,944"
1,2019,"7,713,468,100",1.08 %,"82,377,060",29.8,2.51,52,55.7 %,"4,299,438,618"
2,2018,"7,631,091,040",1.10 %,"83,232,115",29.8,2.51,51,55.3 %,"4,219,817,318"
3,2017,"7,547,858,925",1.12 %,"83,836,876",29.8,2.51,51,54.9 %,"4,140,188,594"
4,2016,"7,464,022,049",1.14 %,"84,224,910",29.8,2.51,50,54.4 %,"4,060,652,683"
5,2015,"7,379,797,139",1.19 %,"84,594,707",30,2.52,50,54.0 %,"3,981,497,663"
6,2010,"6,956,823,603",1.24 %,"82,983,315",28,2.58,47,51.7 %,"3,594,868,146"
7,2005,"6,541,907,027",1.26 %,"79,682,641",27,2.65,44,49.2 %,"3,215,905,863"
8,2000,"6,143,493,823",1.35 %,"79,856,169",26,2.78,41,46.7 %,"2,868,307,513"
9,1995,"5,744,212,979",1.52 %,"83,396,384",25,3.01,39,44.8 %,"2,575,505,235"
10,1990,"5,327,231,061",1.81 %,"91,261,864",24,3.44,36,43.0 %,"2,290,228,096"
11,1985,"4,870,921,740",1.79 %,"82,583,645",23,3.59,33,41.2 %,"2,007,939,063"
12,1980,"4,458,003,514",1.79 %,"75,704,582",23,3.86,30,39.3 %,"1,754,201,029"
13,1975,"4,079,480,606",1.97 %,"75,808,712",22,4.47,27,37.7 %,"1,538,624,994"
14,1970,"3,700,437,046",2.07 %,"72,170,690",22,4.93,25,36.6 %,"1,354,215,496"
15,1965,"3,339,583,597",1.93 %,"60,926,770",22,5.02,22,N.A.,N.A.
16,1960,"3,034,949,748",1.82 %,"52,385,962",23,4.90,20,33.7 %,"1,023,845,517"
17,1955,"2,773,019,936",1.80 %,"47,317,757",23,4.97,19,N.A.,N.A.

In [14]:
df.loc[0, 'Population']

'7,794,798,739'

In [15]:
df.iloc[0, 1]

'7,794,798,739'

In [16]:
df.sort_values(by=['Median Age'])

,Year (July 1),Population,Yearly % Change,Yearly Change,Median Age,Fertility Rate,Density (P/Km²),Urban Pop %,Urban Population
15,1965,"3,339,583,597",1.93 %,"60,926,770",22,5.02,22,N.A.,N.A.
14,1970,"3,700,437,046",2.07 %,"72,170,690",22,4.93,25,36.6 %,"1,354,215,496"
13,1975,"4,079,480,606",1.97 %,"75,808,712",22,4.47,27,37.7 %,"1,538,624,994"
17,1955,"2,773,019,936",1.80 %,"47,317,757",23,4.97,19,N.A.,N.A.
12,1980,"4,458,003,514",1.79 %,"75,704,582",23,3.86,30,39.3 %,"1,754,201,029"
11,1985,"4,870,921,740",1.79 %,"82,583,645",23,3.59,33,41.2 %,"2,007,939,063"
16,1960,"3,034,949,748",1.82 %,"52,385,962",23,4.90,20,33.7 %,"1,023,845,517"
10,1990,"5,327,231,061",1.81 %,"91,261,864",24,3.44,36,43.0 %,"2,290,228,096"
9,1995,"5,744,212,979",1.52 %,"83,396,384",25,3.01,39,44.8 %,"2,575,505,235"
8,2000,"6,143,493,823",1.35 %,"79,856,169",26,2.78,41,46.7 %,"2,868,307,513"
7,2005,"6,541,907,027",1.26 %,"79,682,641",27,2.65,44,49.2 %,"3,215,905,863"
6,2010,"6,956,823,603",1.24 %,"82,983,315",28,2.58,47,51.7 %,"3,594,868,146"
4,2016,"7,464,022,049",1.14 %,"84,224,910",29.8,2.51,50,54.4 %,"4,060,652,683"
3,2017,"7,547,858,925",1.12 %,"83,836,876",29.8,2.51,51,54.9 %,"4,140,188,594"
2,2018,"7,631,091,040",1.10 %,"83,232,115",29.8,2.51,51,55.3 %,"4,219,817,318"
1,2019,"7,713,468,100",1.08 %,"82,377,060",29.8,2.51,52,55.7 %,"4,299,438,618"
5,2015,"7,379,797,139",1.19 %,"84,594,707",30,2.52,50,54.0 %,"3,981,497,663"
0,2020,"7,794,798,739",1.05 %,"81,330,639",30.9,2.47,52,56.2 %,"4,378,993,944"

In [ ]:
#exports the data as an excel file
df.to_excel('word_population.xlsx')

# Project2 : Dealing with multiple pages
maktabkhoone

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = 'https://maktabkhooneh.org/learn/%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%DB%8C-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-mk76/?p=1&'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'lxml')

In [ ]:
courses = soup.find_all('div', class_ = 'side-margin bottom-margin js-filter-item active-item')

In [ ]:
courses

In [ ]:
len(courses)

In [ ]:
print(courses[0].prettify())

In [ ]:
courses[0]['title']

In [ ]:
courses[0].find('div', class_ = 'course-card__title').text

In [ ]:
courses[0]['data-filter']

In [ ]:
courses[0].find('div', class_ = 'course-card__uni-title')

In [ ]:
print(courses[0].find('div', class_ = 'course-card__uni-title').text)

In [ ]:
courses[0].find('div', class_ = 'course-card__teacher').text

In [ ]:
courses[0].find('div', class_ = 'course-card__teacher').text.strip()

In [ ]:
courses[0].find('a', class_ = 'course-card__wrapper')

In [ ]:
courses[0].find('a', class_ = 'course-card__wrapper')['href']

In [ ]:
print('https://maktabkhooneh.org'+courses[0].find('a', class_ = 'course-card__wrapper')['href'])

In [ ]:
for course in courses:
    print('عنوان:', course['title'])
    print('مدرس:', course.find('div', class_ = 'course-card__teacher').text.strip())
    print('آموزشگاه:', course.find('div', class_ = 'course-card__uni-title').text)
    print('لینک', 'https://maktabkhooneh.org'+course.find('a', class_ = 'course-card__wrapper')['href'])

In [ ]:
for course in courses:
    try:
        print('عنوان:', course['title'])
    except:
        print('عنوان:', 'نامعلوم')
    
    try:
        print('مدرس:', course.find('div', class_ = 'course-card__teacher').text.strip())
    except:
        print('مدرس:', 'نامعلوم')
    
    try:
        print('آموزشگاه:', course.find('div', class_ = 'course-card__uni-title').text)
    except:
        print('آموزشگاه:', 'نامعلوم')
        
    try:
        print('لینک', 'https://maktabkhooneh.org'+course.find('a', class_ = 'course-card__wrapper')['href'])
    except:
        print('لینک', 'نامعلوم')

In [ ]:
for i in range(1,6):
    url = f'https://maktabkhooneh.org/learn/%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%DB%8C-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-mk76/?p={i}&'
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'lxml')

    courses = soup.find_all('div', class_ = 'side-margin bottom-margin js-filter-item active-item')

    for course in courses:
        try:
            print('عنوان:', course['title'])
        except:
            print('عنوان:', 'نامعلوم')

        try:
            print('مدرس:', course.find('div', class_ = 'course-card__teacher').text.strip())
        except:
            print('مدرس:', 'نامعلوم')

        try:
            print('آموزشگاه:', course.find('div', class_ = 'course-card__uni-title').text)
        except:
            print('آموزشگاه:', 'نامعلوم')

        try:
            print('لینک', 'https://maktabkhooneh.org'+course.find('a', class_ = 'course-card__wrapper')['href'])
        except:
            print('لینک', 'نامعلوم')

In [ ]:
import pandas as pd

data = []
#gets all our data within the table and adds it to our dataframe
for i in range(1,6):
    url = f'https://maktabkhooneh.org/learn/%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%DB%8C-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-mk76/?p={i}&'
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'lxml')

    courses = soup.find_all('div', class_ = 'side-margin bottom-margin js-filter-item active-item')
    
    for course in courses:
        row_data = []
        try:
            row_data.append(course['title'])
        except:
            row_data.append('')

        try:
            row_data.append(course.find('div', class_ = 'course-card__teacher').text.strip())
        except:
            row_data.append('')

        try:
            row_data.append(course.find('div', class_ = 'course-card__uni-title').text)
        except:
            row_data.append('')

        try:
            row_data.append('https://maktabkhooneh.org'+course.find('a', class_ = 'course-card__wrapper')['href'])
        except:
            row_data.append('')
            
        data.append(row_data)

In [ ]:
print(data)

In [ ]:
headers = ['عنوان', 'مدرس', 'آموزشگاه', 'لینک']
#Creates a dataframe using the column headers from our table
df = pd.DataFrame(data, columns = headers)
df

In [ ]:
df.head(50)

In [ ]:
#exports the data as a xlsx
df.to_excel('maktabkhoone.xlsx')

In [ ]:
print(df.loc[0, 'لینک']+'purchase/?type=FULL')

In [ ]:
price_url = df.loc[0, 'لینک']+'purchase/?type=FULL'
price_page = requests.get(price_url)
price_soup = BeautifulSoup(price_page.text, 'html.parser')
print(price_soup.find('span', {'id' : 'final_value'}).text)

In [ ]:
int('259,000 تومان'.split()[0].replace(',',''))

In [ ]:
import pandas as pd

data = []
#gets all our data within the table and adds it to our dataframe
for i in range(1,6):
    url = f'https://maktabkhooneh.org/learn/%D8%B2%D8%A8%D8%A7%D9%86%D9%87%D8%A7%DB%8C-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87-%D9%86%D9%88%DB%8C%D8%B3%DB%8C-mk76/?p={i}&'
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'lxml')

    courses = soup.find_all('div', class_ = 'side-margin bottom-margin js-filter-item active-item')
    
    for course in courses:
        row_data = []
        try:
            row_data.append(course['title'])
        except:
            row_data.append('')

        try:
            row_data.append(course.find('div', class_ = 'course-card__teacher').text.strip())
        except:
            row_data.append('')

        try:
            row_data.append(course.find('div', class_ = 'course-card__uni-title').text)
        except:
            row_data.append('')

        try:
            row_data.append('https://maktabkhooneh.org'+course.find('a', class_ = 'course-card__wrapper')['href'])
        except:
            row_data.append('')
            
        price_url ='https://maktabkhooneh.org'+course.find('a', class_ = 'course-card__wrapper')['href']+'purchase/?type=FULL'
        price_page = requests.get(price_url)
        price_soup = BeautifulSoup(price_page.text, 'html.parser')
        try:
            p = price_soup.find('span', {'id' : 'final_value'}).text
            row_data.append(int(p.split()[0].replace(',','')))
        except:
            row_data.append(0)
            
        data.append(row_data)

In [ ]:
headers = ['عنوان', 'مدرس', 'آموزشگاه', 'لینک', 'قیمت']
#Creates a dataframe using the column headers from our table
df = pd.DataFrame(data, columns = headers)

In [ ]:
df.head(50)

In [ ]:
df.sort_values(by=['قیمت']).tail(50)

# Javascript driven webpages

In [1]:
# Web driver is a part of selenium. Web driver is basically the core of selenium.
from selenium import webdriver

# access that Web driver using Web driver chrome
driver = webdriver.Chrome('chromedriver.exe')  # we download it before
driver.get('https://bama.ir/car/renault-sanderostepway')

<ipython-input-1-77979d638f40>:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('chromedriver.exe')  # we download it before

WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: chrome=101.0.4951.54)
Stacktrace:
Backtrace:
	Ordinal0 [0x0050B8F3+2406643]
	Ordinal0 [0x0049AF31+1945393]
	Ordinal0 [0x0038C748+837448]
	Ordinal0 [0x00388EE8+823016]
	Ordinal0 [0x0037E0BD+778429]
	Ordinal0 [0x0037EC9A+781466]
	Ordinal0 [0x0037E2CA+778954]
	Ordinal0 [0x0037D8A6+776358]
	Ordinal0 [0x0037C7C5+772037]
	Ordinal0 [0x0037CC9D+773277]
	Ordinal0 [0x0038DF4A+843594]
	Ordinal0 [0x003E4D3D+1199421]
	Ordinal0 [0x003D427C+1131132]
	Ordinal0 [0x003E4682+1197698]
	Ordinal0 [0x003D4096+1130646]
	Ordinal0 [0x003AE636+976438]
	Ordinal0 [0x003AF546+980294]
	GetHandleVerifier [0x00779612+2498066]
	GetHandleVerifier [0x0076C920+2445600]
	GetHandleVerifier [0x005A4F2A+579370]
	GetHandleVerifier [0x005A3D36+574774]
	Ordinal0 [0x004A1C0B+1973259]
	Ordinal0 [0x004A6688+1992328]
	Ordinal0 [0x004A6775+1992565]
	Ordinal0 [0x004AF8D1+2029777]
	BaseThreadInitThunk [0x758A6739+25]
	RtlGetFullPathName_UEx [0x76FC8E7F+1215]
	RtlGetFullPathName_UEx [0x76FC8E4D+1165]